### ISSUE TITLE
Unknown command.

### ISSUE THREAD

**Issue by s00ny5** [dukaev/ipv4-ipv6-proxy#17]
Another issue.

I tried to make 3k 4k 5k proxies and all the time I got this:

![image](https://user-images.githubusercontent.com/30322461/81978606-72666380-9634-11ea-8035-e38115367d53.png)

that`s a part of the "password" as I changed from random.

![image](https://user-images.githubusercontent.com/30322461/81978715-988c0380-9634-11ea-927f-1cbc21268458.png)

Regards

**Comment by dukaev** [comment]
Did you test with 100 or 500? 4k is a lot

**Comment by s00ny5** [comment]
I`ll test now. I know is a lot but that is what I need :) actually 7500

Regards

**Comment by dukaev** [comment]
😮

**Comment by s00ny5** [comment]
worked with 1k. any idea what cause the problem if I use bigger ?

**Comment by dukaev** [comment]
part of data generation needs to rewrite in another language. golang for example

**Comment by s00ny5** [comment]
if only I knew wtf is that XD

**Comment by s00ny5** [comment]
Also what types are this ? socks or http ?

**Comment by jonjonfood88** [comment]
Hey,
Im having problems installing the scripts as followed in the video ... kept getting error 
Example: proxy -i127.0.0.1

Service not started on line: 14
Command: 'proxy' failed with code 40, line 14
  adding: proxy.txt (deflated 65%)

Is there any solution to it?
Thanks

**Comment by dukaev** [comment]
Hello. I don't know. I don't have time to maintain this

**Comment by jonjonfood88** [comment]
do you know how to add additional IPv6 into Vultr?

**Comment by huseyinalp** [comment]
I have similar error. Normally, I have tested on hetzner cloud but I assumed that It will work as expected on Vultr and I have also tried that way but I couldn't succeed.

Logs;
:affe:6bda:ae28:3a2b: Resolver Error 0 (no error)
:5ae8:2ff6:4757:7f38: Resolver Error 0 (no error)
:6260:3ba4:87d4:44b4: Resolver Error 0 (no error)
:b422:0c10:2657:25fd: Resolver Error 0 (no error)
:dafe:69ba:b986:0f03: Resolver Error 0 (no error)
:21a8:1a9e:8b63:9dbe: Resolver Error 0 (no error)
:abb9:6b10:0b87:36d1: Resolver Error 0 (no error)
:f0f4:2d63:0b3d:9d6b: Resolver Error 0 (no error)
:206c:2ac5:7553:ef57: Resolver Error 0 (no error)
Starting 3Proxy

proxy of 3proxy-0.8.6 (160307165135)
Usage: proxy options
Available options are:
 -u never ask for username
 -u2 always ask for username
 -fFORMAT logging format (see documentation)
 -l log to stderr
 -lFILENAME log to FILENAME
 -b(BUFSIZE) size of network buffer (default 4096 for TCP, 16384 for UDP)
 -S(STACKSIZE) value to add to default client thread stack size
 -t be silent (do not log service start/stop)
 -iIP ip address or internal interface (clients are expected to connect)
 -eIP ip address or external interface (outgoing connection will have this)
 -rHOST:PORT Use IP:port for connect back proxy instead of listen port
 -RHOST:PORT Use PORT to listen connect back proxy connection to pass data to
 -4 Use IPv4 for outgoing connections
 -6 Use IPv6 for outgoing connections
 -46 Prefer IPv4 for outgoing connections, use both IPv4 and IPv6
 -64 Prefer IPv6 for outgoing connections, use both IPv4 and IPv6
 -pPORT - service port to accept connections
 -RIP:PORT - connect back IP:PORT to listen and accept connections
 -rIP:PORT - connect back IP:PORT to establish connect back connection
 -n - no NTLM support
	Example: proxy -i127.0.0.1

Service not started on line: 14
Command: 'proxy' failed with code 40, line 14

If someone find  out solution, please let us know.
Thanks
