### ISSUE TITLE
proxy cant be used

### ISSUE THREAD

**Issue by dederaditya** [dukaev/ipv4-ipv6-proxy#6]
no internet connection, any idea to make this work?

using Amazon EC2

**Comment by dukaev** [comment]
Sorry. At the moment it works on vultr

**Comment by dederaditya** [comment]
Wow thank you for replying to me :) I spent 3 hours to figure it out. I think Amazon is too complicated for this. I hope you gonna make fix

**Comment by dederaditya** [comment]
so on vultr i just need to run the script?

**Comment by dukaev** [comment]
Yes. Like https://www.youtube.com/watch?v=EKBJHSTmT4w
I have plan to move it to docker. And then it will work everywhere

**Comment by dederaditya** [comment]
I will be waiting for it :) I dont understand scripting and each time I got errors I search the whole text on Google

**Comment by dederaditya** [comment]
Hello, my friend tested this on Vultr vps, but the IPv6 is not accesable in other computer.

**Comment by dederaditya** [comment]
VPS shutted down because too many request any idea how to figure it out?

**Comment by dederaditya** [comment]
Tested it on Vultr VPS, but 3proxy crashes after I use the proxies. Is there any configuration to make the proxies stable? 

maxcons 250 (default was 1000)

**Comment by dukaev** [comment]
Maybe do you need a more powerful machine?

**Comment by ItsDaWither** [comment]
No, I am having this same problem too. 

Additionally, this script sets the maxcon to 10000, but the default ulimit is 1024, and 3proxy asks that the ulimit be twice the maxcon. A section needs to be added to the script for increasing the ulimit for maximum performance.

> Tested it on Vultr VPS, but 3proxy crashes after I use the proxies. Is there any configuration to make the proxies stable?
> 
> maxcons 250 (default was 1000)

You need to add a line to the config, `stacksize <number>` (where number is at least 8192) as the default stacksize is usually too small and will result in 3proxy crashing due to not being able to load the response.

**Comment by dukaev** [comment]
@ItsDaWither cool! Thank you!
Can you please create PR?

**Comment by ItsDaWither** [comment]
I can't figure out how to make a pull request, sorry.

I believe however in the gen_3proxy function just add a line below `setuid 65535` that says `stacksize 262144`

Its a large stacksize that will consume a little more RAM, but arguably worth it in order to get 3proxy to work with most sites without crashing.

I don't know how to increase the ulimit for a service, though I believe it involves editing the init file for the service and adding the line `LimitNOFILE=65536` [based on what I could gather from this stackoverflow post.](https://unix.stackexchange.com/questions/345595/how-to-set-ulimits-on-service-with-systemd)

**Comment by dukaev** [comment]
@dederaditya can you check please https://github.com/dukaev/ipv4-ipv6-proxy/pull/7? Right?

**Comment by dukaev** [comment]
@dederaditya can you check with updated version https://github.com/dukaev/ipv4-ipv6-proxy/pull/7

You need install like this:
`https://raw.githubusercontent.com/dukaev/ipv6_proxy/fix/mem-limit/scripts/install.sh`

**Comment by ItsDaWither** [comment]
@dukaev The stacksize change works great!

However, I don't think the ulimit command actually did anything...

Running the command `sudo systemctl status 3proxy` while the server is running results in this line appearing at the bottom...

`Mar 31 04:43:28 guest 3proxy[8968]: [line 2] Warning: current open file ulimits are too low (cur: 1024/max: 4096), maxconn requires at least 2000 for every running service. Configure ulimits according to system documentation`

The maxconn is set to 1000, so I don't think that ulimit change actually did anything. 

I did find [this stackoverflow question](https://serverfault.com/questions/628610/increasing-nproc-for-processes-launched-by-systemd-on-centos-7/678861#678861) that suggests that a systemd file needs to be edited for the service. However I was not able to find those configuration files on the server and they don't seem to be at the file paths in the article. I am not sure where it is or what files need to be edited.

**Comment by ItsDaWither** [comment]
I have created PR #8 that updates the ulimit of the 3proxy service via the `prlimit` command, which I found [here.](https://superuser.com/questions/1289345/why-doesnt-ulimit-n-work-when-called-inside-a-script)

**Comment by dukaev** [comment]
@dederaditya I see that you worked on PR. 🙂
You can write to me  Telegram: [t.me/current_user](t.me/current_user) for help creating PR

**Comment by ItsDaWither** [comment]
I have found a new bug in that restarting the VPS poses a problem, as the system is unable to start the service.

Some further research by running `systemctl is-enabled 3proxy` results in this output:

`3proxy.service is not a native service, redirecting to /sbin/chkconfig.
Executing /sbin/chkconfig 3proxy --level=5
enabled`

I believe that this is because 3proxy is designed as a SysV service and not a `systemd` service, and therefore the script needs to be edited to use chkconfig to start 3proxy instead of relying on `systemctl` and `systemd`.

**Comment by dukaev** [comment]
@ItsDaWither thank you for working on this problem 👍
